<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var app\models\IzinDokter $model
*/
$copyParams = $model->attributes;

$this->title =  'Izin Dokter';
$this->params['breadcrumbs'][] = ['label' =>  'Izin Dokters', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id_no_izin, 'url' => ['view', 'id_no_izin' => $model->id_no_izin]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud izin-dokter-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h1>
       Izin Dokter
        <small>
            <?= $model->id_no_izin ?>
        </small>
    </h1>


    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>
            <?= Html::a(
            '<span class="glyphicon glyphicon-pencil"></span> ' . 'Edit',
            [ 'update', 'id_no_izin' => $model->id_no_izin],
            ['class' => 'btn btn-info']) ?>

            <?= Html::a(
            '<span class="glyphicon glyphicon-copy"></span> ' . 'Copy',
            ['create', 'id_no_izin' => $model->id_no_izin, 'IzinDokter'=>$copyParams],
            ['class' => 'btn btn-success']) ?>

            <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . 'New',
            ['create'],
            ['class' => 'btn btn-success']) ?>
        </div>

        <div class="pull-right">
            <?= Html::a('<span class="glyphicon glyphicon-list"></span> '
            . 'Full list', ['index'], ['class'=>'btn btn-default']) ?>
        </div>

    </div>

    <hr />

    <?php $this->beginBlock('app\models\IzinDokter'); ?>

    
    <?= DetailView::widget([
    'model' => $model,
    'attributes' => [
            'no_izin',
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'keahlian',
    'value' => ($model->getKeahlian0()->one() ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['spesialis/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->getKeahlian0()->one()->id, ['spesialis/view', 'id' => $model->getKeahlian0()->one()->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'IzinDokter'=>['keahlian' => $model->keahlian]])
        : 
        '<span class="label label-warning">?</span>'),
],
    ],
    ]); ?>

    
    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . 'Delete', ['delete', 'id_no_izin' => $model->id_no_izin],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . 'Are you sure to delete this item?' . '',
    'data-method' => 'post',
    ]); ?>
    <?php $this->endBlock(); ?>


    
<?php $this->beginBlock('Dokters'); ?>
<div style='position: relative'>
<div style='position:absolute; right: 0px; top: 0px;'>
  <?= Html::a(
            '<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Dokters',
            ['dokter/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . 'New' . ' Dokter',
            ['dokter/create', 'Dokter' => ['id_no_izin' => $model->id_no_izin]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
</div>
</div>
<?php Pjax::begin(['id'=>'pjax-Dokters', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-Dokters ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>
<?=
 '<div class="table-responsive">'
 . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider([
        'query' => $model->getDokters(),
        'pagination' => [
            'pageSize' => 20,
            'pageParam'=>'page-dokters',
        ]
    ]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => 'First',
        'lastPageLabel'  => 'Last'
    ],
    'columns' => [
 [
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'dokter' . '/' . $action;
        $params['Dokter'] = ['id_no_izin' => $model->primaryKey()[0]];
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => 'dokter'
],
        'id_dokter',
        'email:email',
        'alamat_rumah',
        'alamat_praktik',
        'nama_dokter',
        'no_telp',
        'password',
        'id_kota',
        'id_provinsi',
]
])
 . '</div>' 
?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


    <?= Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [
 [
    'label'   => '<b class=""># '.$model->id_no_izin.'</b>',
    'content' => $this->blocks['app\models\IzinDokter'],
    'active'  => true,
],
[
    'content' => $this->blocks['Dokters'],
    'label'   => '<small>Dokters <span class="badge badge-default">'.count($model->getDokters()->asArray()->all()).'</span></small>',
    'active'  => false,
],
 ]
                 ]
    );
    ?>
</div>
