<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace frontend\models\base;

use Yii;

/**
 * This is the base-model class for table "daftar_penyakit".
 *
 * @property string $nama_penyakit
 * @property integer $id
 *
 * @property \frontend\models\Riwayat[] $riwayats
 * @property string $aliasModel
 */
abstract class DaftarPenyakit extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'daftar_penyakit';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama_penyakit'], 'required'],
            [['nama_penyakit'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'nama_penyakit' => 'Nama Penyakit',
            'id' => 'ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRiwayats()
    {
        return $this->hasMany(\frontend\models\Riwayat::className(), ['diagnosa' => 'id']);
    }




}
