<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace frontend\models\base;

use Yii;

/**
 * This is the base-model class for table "riwayat".
 *
 * @property integer $id_riwayat
 * @property integer $id_pasien
 * @property integer $id_dokter
 * @property integer $umur
 * @property integer $berat_badan
 * @property integer $tinggi_badan
 * @property string $riwayat_kesehatan_keluarga
 * @property string $keluhan_utama
 * @property integer $diagnosa
 * @property string $larangan
 * @property string $note
 * @property string $tgl_periksa
 * @property string $perawatan
 *
 * @property \frontend\models\Pasien $idPasien
 * @property \frontend\models\Dokter $idDokter
 * @property \frontend\models\DaftarPenyakit $diagnosa0
 * @property string $aliasModel
 */
abstract class Riwayat extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'riwayat';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_pasien', 'id_dokter', 'diagnosa', 'perawatan'], 'required'],
            [['id_pasien', 'id_dokter', 'umur', 'berat_badan', 'tinggi_badan', 'diagnosa'], 'integer'],
            [['riwayat_kesehatan_keluarga', 'keluhan_utama', 'larangan', 'note'], 'string'],
            [['tgl_periksa'], 'safe'],
            [['perawatan'], 'string', 'max' => 25],
            [['id_pasien'], 'exist', 'skipOnError' => true, 'targetClass' => \frontend\models\Pasien::className(), 'targetAttribute' => ['id_pasien' => 'id_pasien']],
            [['id_dokter'], 'exist', 'skipOnError' => true, 'targetClass' => \frontend\models\Dokter::className(), 'targetAttribute' => ['id_dokter' => 'id_dokter']],
            [['diagnosa'], 'exist', 'skipOnError' => true, 'targetClass' => \frontend\models\DaftarPenyakit::className(), 'targetAttribute' => ['diagnosa' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_riwayat' => 'Id Riwayat',
            'id_pasien' => 'Id Pasien',
            'id_dokter' => 'Id Dokter',
            'umur' => 'Umur',
            'berat_badan' => 'Berat Badan',
            'tinggi_badan' => 'Tinggi Badan',
            'riwayat_kesehatan_keluarga' => 'Riwayat Kesehatan Keluarga',
            'keluhan_utama' => 'Keluhan Utama',
            'diagnosa' => 'Diagnosa',
            'larangan' => 'Larangan',
            'note' => 'Note',
            'tgl_periksa' => 'Tgl Periksa',
            'perawatan' => 'Perawatan',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdPasien()
    {
        return $this->hasOne(\frontend\models\Pasien::className(), ['id_pasien' => 'id_pasien']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdDokter()
    {
        return $this->hasOne(\frontend\models\Dokter::className(), ['id_dokter' => 'id_dokter']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDiagnosa0()
    {
        return $this->hasOne(\frontend\models\DaftarPenyakit::className(), ['id' => 'diagnosa']);
    }




}
