<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var app\models\Riwayat $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="riwayat-form">

    <?php $form = ActiveForm::begin([
    'id' => 'Riwayat',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error'
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            

<!-- attribute id_pasien -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'id_pasien')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\Pasien::find()->all(), 'id_pasien', 'id_pasien'),
    [
        'prompt' => 'Select',
        'disabled' => (isset($relAttributes) && isset($relAttributes['id_pasien'])),
    ]
); ?>

<!-- attribute id_dokter -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'id_dokter')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\Dokter::find()->all(), 'id_dokter', 'id_dokter'),
    [
        'prompt' => 'Select',
        'disabled' => (isset($relAttributes) && isset($relAttributes['id_dokter'])),
    ]
); ?>

<!-- attribute diagnosa -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'diagnosa')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\DaftarPenyakit::find()->all(), 'id', 'id'),
    [
        'prompt' => 'Select',
        'disabled' => (isset($relAttributes) && isset($relAttributes['diagnosa'])),
    ]
); ?>

<!-- attribute perawatan -->
			<?= $form->field($model, 'perawatan')->textInput(['maxlength' => true]) ?>

<!-- attribute umur -->
			<?= $form->field($model, 'umur')->textInput() ?>

<!-- attribute berat_badan -->
			<?= $form->field($model, 'berat_badan')->textInput() ?>

<!-- attribute tinggi_badan -->
			<?= $form->field($model, 'tinggi_badan')->textInput() ?>

<!-- attribute riwayat_kesehatan_keluarga -->
			<?= $form->field($model, 'riwayat_kesehatan_keluarga')->textarea(['rows' => 6]) ?>

<!-- attribute keluhan_utama -->
			<?= $form->field($model, 'keluhan_utama')->textarea(['rows' => 6]) ?>

<!-- attribute larangan -->
			<?= $form->field($model, 'larangan')->textarea(['rows' => 6]) ?>

<!-- attribute note -->
			<?= $form->field($model, 'note')->textarea(['rows' => 6]) ?>

<!-- attribute tgl_periksa -->
			<?= $form->field($model, 'tgl_periksa')->textInput() ?>
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                    'encodeLabels' => false,
                    'items' => [ 
                        [
    'label'   =>  'Riwayat',
    'content' => $this->blocks['main'],
    'active'  => true,
],
                    ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? 'Create' : 'Save'),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

