<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var app\models\Riwayat $model
*/
$copyParams = $model->attributes;

$this->title = 'Riwayat';
$this->params['breadcrumbs'][] = ['label' => Yii::t('models', 'Riwayats'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id_riwayat, 'url' => ['view', 'id_riwayat' => $model->id_riwayat]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud riwayat-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h1>
       Riwayat
        <small>
            <?= $model->id_riwayat ?>
        </small>
    </h1>


    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>
            <?= Html::a(
            '<span class="glyphicon glyphicon-pencil"></span> ' . 'Edit',
            [ 'update', 'id_riwayat' => $model->id_riwayat],
            ['class' => 'btn btn-info']) ?>

            <?= Html::a(
            '<span class="glyphicon glyphicon-copy"></span> ' . 'Copy',
            ['create', 'id_riwayat' => $model->id_riwayat, 'Riwayat'=>$copyParams],
            ['class' => 'btn btn-success']) ?>

            <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . 'New',
            ['create'],
            ['class' => 'btn btn-success']) ?>
        </div>

        <div class="pull-right">
            <?= Html::a('<span class="glyphicon glyphicon-list"></span> '
            . 'Full list', ['index'], ['class'=>'btn btn-default']) ?>
        </div>

    </div>

    <hr />

    <?php $this->beginBlock('app\models\Riwayat'); ?>

    
    <?= DetailView::widget([
    'model' => $model,
    'attributes' => [
    // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'id_pasien',
    'value' => ($model->getIdPasien()->one() ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['pasien/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->getIdPasien()->one()->id_pasien, ['pasien/view', 'id_pasien' => $model->getIdPasien()->one()->id_pasien,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Riwayat'=>['id_pasien' => $model->id_pasien]])
        : 
        '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'id_dokter',
    'value' => ($model->getIdDokter()->one() ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['dokter/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->getIdDokter()->one()->id_dokter, ['dokter/view', 'id_dokter' => $model->getIdDokter()->one()->id_dokter,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Riwayat'=>['id_dokter' => $model->id_dokter]])
        : 
        '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'diagnosa',
    'value' => ($model->getDiagnosa0()->one() ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['daftar-penyakit/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->getDiagnosa0()->one()->id, ['daftar-penyakit/view', 'id' => $model->getDiagnosa0()->one()->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Riwayat'=>['diagnosa' => $model->diagnosa]])
        : 
        '<span class="label label-warning">?</span>'),
],
        'perawatan',
        'umur',
        'berat_badan',
        'tinggi_badan',
        'riwayat_kesehatan_keluarga:ntext',
        'keluhan_utama:ntext',
        'larangan:ntext',
        'note:ntext',
        'tgl_periksa',
    ],
    ]); ?>

    
    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . 'Delete', ['delete', 'id_riwayat' => $model->id_riwayat],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . 'Are you sure to delete this item?' . '',
    'data-method' => 'post',
    ]); ?>
    <?php $this->endBlock(); ?>


    
    <?= Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [
 [
    'label'   => '<b class=""># '.$model->id_riwayat.'</b>',
    'content' => $this->blocks['app\models\Riwayat'],
    'active'  => true,
],
 ]
                 ]
    );
    ?>
</div>
