<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\controllers\base;

use app\models\IzinDokter;
    use backend\models\IzinDokterSearch;
use yii\web\Controller;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\filters\AccessControl;
use dmstr\bootstrap\Tabs;

/**
* IzinDokterController implements the CRUD actions for IzinDokter model.
*/
class IzinDokterController extends Controller
{


/**
* @var boolean whether to enable CSRF validation for the actions in this controller.
* CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
*/
public $enableCsrfValidation = false;


/**
* Lists all IzinDokter models.
* @return mixed
*/
public function actionIndex()
{
    $searchModel  = new IzinDokterSearch;
    $dataProvider = $searchModel->search($_GET);

Tabs::clearLocalStorage();

Url::remember();
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->render('index', [
'dataProvider' => $dataProvider,
    'searchModel' => $searchModel,
]);
}

/**
* Displays a single IzinDokter model.
* @param integer $id_no_izin
*
* @return mixed
*/
public function actionView($id_no_izin)
{
\Yii::$app->session['__crudReturnUrl'] = Url::previous();
Url::remember();
Tabs::rememberActiveState();

return $this->render('view', [
'model' => $this->findModel($id_no_izin),
]);
}

/**
* Creates a new IzinDokter model.
* If creation is successful, the browser will be redirected to the 'view' page.
* @return mixed
*/
public function actionCreate()
{
$model = new IzinDokter;

try {
if ($model->load($_POST) && $model->save()) {
return $this->redirect(['view', 'id_no_izin' => $model->id_no_izin]);
} elseif (!\Yii::$app->request->isPost) {
$model->load($_GET);
}
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
$model->addError('_exception', $msg);
}
return $this->render('create', ['model' => $model]);
}

/**
* Updates an existing IzinDokter model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $id_no_izin
* @return mixed
*/
public function actionUpdate($id_no_izin)
{
$model = $this->findModel($id_no_izin);

if ($model->load($_POST) && $model->save()) {
return $this->redirect(Url::previous());
} else {
return $this->render('update', [
'model' => $model,
]);
}
}

/**
* Deletes an existing IzinDokter model.
* If deletion is successful, the browser will be redirected to the 'index' page.
* @param integer $id_no_izin
* @return mixed
*/
public function actionDelete($id_no_izin)
{
try {
$this->findModel($id_no_izin)->delete();
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
\Yii::$app->getSession()->addFlash('error', $msg);
return $this->redirect(Url::previous());
}

// TODO: improve detection
$isPivot = strstr('$id_no_izin',',');
if ($isPivot == true) {
return $this->redirect(Url::previous());
} elseif (isset(\Yii::$app->session['__crudReturnUrl']) && \Yii::$app->session['__crudReturnUrl'] != '/') {
Url::remember(null);
$url = \Yii::$app->session['__crudReturnUrl'];
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->redirect($url);
} else {
return $this->redirect(['index']);
}
}

/**
* Finds the IzinDokter model based on its primary key value.
* If the model is not found, a 404 HTTP exception will be thrown.
* @param integer $id_no_izin
* @return IzinDokter the loaded model
* @throws HttpException if the model cannot be found
*/
protected function findModel($id_no_izin)
{
if (($model = IzinDokter::findOne($id_no_izin)) !== null) {
return $model;
} else {
throw new HttpException(404, 'The requested page does not exist.');
}
}
}
