<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;
use dosamigos\datepicker\DatePicker;
use yii\helpers\ArrayHelper;
use kartik\money\MaskMoney;

/**
 * @var yii\web\View $this
 * @var app\models\MasterKontrak $model
 * @var yii\widgets\ActiveForm $form
 */

?>

<div class="master-kontrak-form">

    <?php $form = ActiveForm::begin([
            'id' => 'MasterKontrak',
            'layout' => 'horizontal',
            'enableClientValidation' => true,
            'errorSummaryCssClass' => 'error-summary alert alert-error'
        ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>


            <!-- attribute nama -->
            <?= $form->field($model, 'nama')->textInput(['maxlength' => true]) ?>

            <!-- attribute id_mitra -->
            <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'id_mitra')->widget(\kartik\select2\Select2::className(), [
                'data' => ArrayHelper::map(app\models\MasterMitra::find()->all(), 'id', 'nama'),
                'disabled' => \Yii::$app->user->identity->role == 6 ? true : false,
                'options' => [
                    'prompt' => 'Pilih Mitra',
                ],
            ])->label('Mitra'); ?>

            <?php if (\Yii::$app->user->identity->role == 6): ?>
                <?= $form->field($model, 'id_mitra', ['template' => '{input}'])->textInput(['style' => 'display:none']); ?>
            <?php endif; ?>

            <!-- attribute nilai_kontrak -->
            <?= $form->field($model, 'nilai_kontrak')->widget(MaskMoney::classname()); ?>

            <!-- attribute tanggal_mulai -->
            <?= $form->field($model, 'tanggal_mulai')->textInput()->widget(DatePicker::className(), ['clientOptions' => [
                'autoclose' => true,
                'format' => 'yyyy-mm-dd'
            ]]); ?>

            <!-- attribute tanggal_berakhir -->
            <?= $form->field($model, 'tanggal_berakhir')->textInput()->widget(DatePicker::className(), ['clientOptions' => [
                'autoclose' => true,
                'format' => 'yyyy-mm-dd'
            ]]); ?>

            <!-- attribute status -->
            <?php
            if (Yii::$app->user->identity->role == 2) {
                ?>
                <?= $form->field($model, 'status')->hiddenInput(['value' => '1'])->label(false) ?>
            <?php } else {
                ?>
                <?= $form->field($model, 'status')->hiddenInput(['value' => '0'])->label(false) ?>
            <?php }

            ?>

            <!-- attribute flag -->
            <?= $form->field($model, 'flag')->hiddenInput(['value' => '1'])->label(false) ?>
        </p>
        <?php $this->endBlock(); ?>

        <?=
        Tabs::widget(
            [
                'encodeLabels' => false,
                'items' => [
                    [
                        'label' => 'MasterKontrak',
                        'content' => $this->blocks['main'],
                        'active' => true,
                    ],
                ]
            ]
        );
        ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
            '<span class="glyphicon glyphicon-check"></span> ' .
            ($model->isNewRecord ? 'Create' : 'Save'),
            [
                'id' => 'save-' . $model->formName(),
                'class' => 'btn btn-success'
            ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

