<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;
use yii\helpers\ArrayHelper;
use dosamigos\datepicker\DatePicker;
use yii\helpers\Url;
use kartik\money\MaskMoney;

/**
 * @var yii\web\View $this
 * @var app\models\MasterKegiatan $model
 * @var yii\widgets\ActiveForm $form
 */

?>

<div class="master-kegiatan-form">

    <?php $form = ActiveForm::begin([
            'id' => 'MasterKegiatan',
            'layout' => 'horizontal',
            'enableClientValidation' => true,
            'errorSummaryCssClass' => 'error-summary alert alert-error'
        ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>


            <!-- attribute id_mitra -->
            <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'id_mitra')->widget(\kartik\select2\Select2::className(), [
                'data' => ArrayHelper::map(app\models\MasterMitra::find()->asArray()->all(), 'id', 'nama'),
                'disabled' => \Yii::$app->user->identity->role == 6 ? true : false,
                'options' => [
                    'prompt' => 'Pilih Mitra',
                    // 'onchange' =>'$.post("'.Yii::$app->urlManager->createUrl('kontrak/lists?id=').'"+$(this).val(),function(data){
                    //     $( "#id_kontrak" ).html( data );
                    // }   )'

                    'onchange' => '
                        $.get( "' . Url::toRoute('/kontrak/lists') . '", { id: $(this).val() } )
                            .done(function( data ) {
                                $( "#' . Html::getInputId($model, 'id_kontrak') . '" ).html( data );
                            }
                        );
                    '
                ],
            ])->label('Mitra'); ?>

            <?php if (\Yii::$app->user->identity->role == 6): ?>
                <?= $form->field($model, 'id_mitra', ['template' => '{input}'])->textInput(['style' => 'display:none']); ?>
            <?php endif; ?>

            <!-- attribute id_jenis -->
            <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'id_jenis')->widget(\kartik\select2\Select2::className(), [
                'data' => ArrayHelper::map(app\models\JenisKegiatan::find()->all(), 'id', 'type_kegiatan'),
                'options' => [
                    'prompt' => 'Pilih Jenis Kegiatan'
                ],
            ])->label('Jenis kegiatan'); ?>

            <!-- $mitra = MasterMitra::findOne($id);
            $kontrak = $mitra-> getMasterKontraks()->all();
            ->widget(\kartik\select2\Select2::className(),[
                            'options'=>[
                                'prompt'=>'Pilih Jenis Kegiatan'
                            ],
                        ])->label('jenis kegiatan'); -->
            <!-- attribute id_kontrak -->
            <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'id_kontrak')->dropDownList(
                [
                    'data' => \Yii::$app->user->identity->role == 6 ?
                        ArrayHelper::map(app\models\MasterKontrak::find()->where(['id_mitra' => \Yii::$app->user->identity->masterMitra->id])->all(), 'id', 'nama') : null,
                    'prompt' => 'Pilih Kontrak'
                ])->label('Nama Kontrak');
            ?>

            <!-- attribute id_tahun_ajar -->
            <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'id_tahun_ajar')->widget(\kartik\select2\Select2::className(), [
                'data' => ArrayHelper::map(app\models\MasterTahunAjar::find()->where(['>', 'akhir', date('Y-m-d')])->all(), 'id', function ($model, $defaultValue) {
                    $formatter = Yii::$app->formatter;
                    return $formatter->asDate($model['awal']) . ' ' . '/' . ' ' . $formatter->asDate($model['akhir']);
                }),
                'options' => [
                    'prompt' => 'Pilih Tahun Ajar',
                ],
            ])->label('Tahun Ajaran'); ?>


            <!-- attribute nominal -->
            <?= $form->field($model, 'nominal')->textInput()->widget(MaskMoney::classname()) ?>

            <!-- attribute tanggal_mulai -->
            <?= $form->field($model, 'tanggal_mulai')->textInput()->widget(DatePicker::className(), ['clientOptions' => [
                'autoclose' => true,
                'format' => 'yyyy-mm-dd'
            ]]); ?>

            <!-- attribute tanggal_selesai -->
            <?= $form->field($model, 'tanggal_selesai')->textInput()->widget(DatePicker::className(), ['clientOptions' => [
                'autoclose' => true,
                'format' => 'yyyy-mm-dd'
            ]]); ?>
            <!-- attribute deskripsi_kegiatan -->
            <?= $form->field($model, 'deskripsi_kegiatan')->textArea(['maxlength' => true]) ?>


            <!-- attribute id_jurusan -->
            <?= $form->field($model, 'id_jurusan')->widget(\kartik\select2\Select2::className(), [
                'data' => ArrayHelper::map(app\models\Jurusan::find()->all(), 'id', 'nama_jurusan'),
                'options' => [
                    'prompt' => 'Pilih Jurusan'
                ],
            ])->label('Jurusan'); ?>

            <!-- attribute flag -->

            <?= $form->field($model, 'flag')->hiddenInput(['value' => '1'])->label(false) ?>
            <!-- attribute status -->

            <?php
            if (Yii::$app->user->identity->role == 2) {
                ?>
                <?= $form->field($model, 'status')->hiddenInput(['value' => '1'])->label(false) ?>
            <?php } else {
                ?>
                <?= $form->field($model, 'status')->hiddenInput(['value' => '0'])->label(false) ?>
            <?php }

            ?>

        </p>
        <?php $this->endBlock(); ?>

        <?=
        Tabs::widget(
            [
                'encodeLabels' => false,
                'items' => [
                    [
                        'label' => 'MasterKegiatan',
                        'content' => $this->blocks['main'],
                        'active' => true,
                    ],
                ]
            ]
        );
        ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
            '<span class="glyphicon glyphicon-check"></span> ' .
            ($model->isNewRecord ? 'Create' : 'Save'),
            [
                'id' => 'save-' . $model->formName(),
                'class' => 'btn btn-success'
            ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>