<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
 * @var yii\web\View $this
 * @var app\models\MasterKegiatan $model
 */
$copyParams = $model->attributes;

$this->title = 'Master Kegiatan';
$this->params['breadcrumbs'][] = ['label' => 'Master Kegiatans', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->idKontrak->nama, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud master-kegiatan-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h1>
        Kegiatan
        <small>
            <?= $model->idKontrak->nama ?>
        </small>
    </h1>


    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>
            <?= Html::a(
                '<span class="glyphicon glyphicon-pencil"></span> ' . 'Edit',
                ['update', 'id' => $model->id],
                ['class' => 'btn btn-info']) ?>

            <?= Html::a(
                '<span class="glyphicon glyphicon-copy"></span> ' . 'Copy',
                ['create', 'id' => $model->id, 'MasterKegiatan' => $copyParams],
                ['class' => 'btn btn-success']) ?>

            <?= Html::a(
                '<span class="glyphicon glyphicon-plus"></span> ' . 'New',
                ['create'],
                ['class' => 'btn btn-success']) ?>
        </div>

        <div class="pull-right">
            <?= Html::a('<span class="glyphicon glyphicon-list"></span> '
                . 'Full list', ['index'], ['class' => 'btn btn-default']) ?>
        </div>

    </div>

    <hr/>

    <?php $this->beginBlock('app\models\MasterKegiatan'); ?>


    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
            [
                'format' => 'html',
                'attribute' => 'id_mitra',
                'value' => Html::a($model->idMitra->nama, ['mitra/view', 'id' => $model->idMitra->id,]),
                'visible' => \Yii::$app->user->identity->role == 6 ? false : true,
            ],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
            [
                'format' => 'html',
                'attribute' => 'id_jenis',
                'value' => $model->idJenis->type_kegiatan,
            ],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
            [
                'format' => 'html',
                'attribute' => 'id_kontrak',
                'value' => Html::a($model->idKontrak->nama, ['mitra/view', 'id' => $model->idKontrak->id,]),
            ],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
            [
                'format' => 'html',
                'attribute' => 'id_tahun_ajar',
                'value' => function ($model) {
                    $formatter = Yii::$app->formatter;
                    return $formatter->asDate($model->idTahunAjar->awal).' / '.$formatter->asDate($model->idTahunAjar->akhir);
                },
            ],
            [
                'attribute' => 'nominal',
                'format' => 'raw',
                'value' => function ($data) {
                    return Yii::$app->runAction('kegiatan/rupiah', ['nilai' => $data->nominal]);
                }
            ],
            'tanggal_mulai:date',
            'tanggal_selesai:date',
            [
                'attribute' => 'status',
                'format' => 'raw',
                'value' => function ($data) {
                    if (Yii::$app->user->identity->role != 2 && $data->status == 0) {
                        return "<span class=\"label bg-red\">Belum di Approve</span>";
                    } else if (Yii::$app->user->identity->role != 2 && $data->status == 1) {
                        return "<span class=\"label bg-green\">Approved</span>";
                    } else if (Yii::$app->user->identity->role == 2 && $data->status == 0) {
                        return "<span class=\"label bg-red\">Belum di Approve</span>";
                    }
                    return "<span class=\"label bg-green\">Approved</span>";
                }
            ],
            [
                'attribute' => 'id_jurusan',
                'value' => $model->idJurusan->nama_jurusan,
            ],
            'deskripsi_kegiatan',
        ],
    ]); ?>


    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . 'Delete', ['delete', 'id' => $model->id],
        [
            'class' => 'btn btn-danger',
            'data-confirm' => '' . 'Are you sure to delete this item?' . '',
            'data-method' => 'post',
        ]); ?>
    <?php $this->endBlock(); ?>



    <?= Tabs::widget(
        [
            'id' => 'relation-tabs',
            'encodeLabels' => false,
            'items' => [
                [
                    'label' => '<b class=""># ' . $model->idKontrak->nama . '</b>',
                    'content' => $this->blocks['app\models\MasterKegiatan'],
                    'active' => true,
                ],
            ]
        ]
    );
    ?>
</div>
