<?=  \kartik\grid\GridView::widget([
    'dataProvider' => $dataProvider,
    //'showFooter'=>TRUE,
    'pager' => [
        'class' => yii\widgets\LinkPager::className(),
        'firstPageLabel' => 'First',
        'lastPageLabel' => 'Last',
    ],
    'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
    'headerRowOptions' => ['class' => 'x'],
    'panel' => [
        'type' => \kartik\grid\GridView::TYPE_PRIMARY,
        'heading' => '<span class="glyphicon glyphicon-book"></span> Beasiswa ',
    ],
    'toolbar' => [
        [
            'content'=> (date('Y-m-d') > date('Y-m-d', strtotime($tahun_ajar->akhir)) && $tahun_ajar->is_calculated == 0) ?
                '<a href="'.\yii\helpers\Url::to(['skenario1/calculate?id='.$tahun_ajar->id]).'" class="btn btn-primary"><i class="fa fa-calculator"></i> Hitung Kuota Fix Mitra</a>' :
                '<a href="'.\yii\helpers\Url::to(['skenario1/calculate?id='.$tahun_ajar->id]).'" class="btn btn-primary disabled" disabled=""><i class="fa fa-calculator"></i> Hitung Kuota Fix Mitra</a>',
            'options' => ['class' => 'btn-group']
        ],
    ],
    'beforeHeader' => [
        [
            'columns' => [
                [
                    'content' => $isEditable['status'] ?
                        '<span class="glyphicon glyphicon-ok text-success"></span> '.$isEditable['message'] :
                        '<span class="glyphicon glyphicon-remove text-warning"></span> '.$isEditable['message'],
                    'options' => [
                        'colspan' => 7, 'class' => $isEditable['status'] ? 'text-center success' : 'text-center warning',
                    ],
                ],
            ],
            'options' => ['class' => 'skip-export']
        ]
    ],
    'columns' => [
        ['class' => 'kartik\grid\SerialColumn'],
        // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
        [
            'class' => yii\grid\DataColumn::className(),
            'attribute' => 'nama',
            'value' => function ($model) {
                return \yii\helpers\Html::a($model->nama, ['mitra/view', 'id' => $model->id,], ['data-pjax' => 0]);
            },
            'format' => 'raw',
        ],
        [
            'attribute' => 'nominal',
            'format' => 'raw',
            'value' => function ($model) {
                return Yii::$app->runAction('kegiatan/rupiah', ['nilai' => $model->nominal]);
            },
        ],
        [
            'headerOptions' => ['style' => 'width:5%'],
            'attribute' => 'kuota',
            'format' => 'raw',
            'value' => function($model) {
                return ceil($model->kuota);
            },
        ],
        [
            'class' => 'kartik\grid\EditableColumn',
            'hAlign' => \kartik\grid\GridView::ALIGN_RIGHT,
            'attribute' => 'diambil',
            'format' => 'raw',
            'editableOptions' => function ($model, $key, $index) use ($tahun_ajar) {
                if (date('Y-m-d') > date('Y-m-d', strtotime($tahun_ajar->akhir))) {
                    return [
                        'format' => \kartik\editable\Editable::FORMAT_BUTTON,
                        'inputType' => \kartik\editable\Editable::INPUT_TEXT,
                        'asPopover' => false,
                        'ajaxSettings' => [
                            'url' => \yii\helpers\Url::to(['skenario1/alokasi-beasiswa?id='.$model->id_skenario]),
                        ],
                        'pluginEvents' => [
                            'editableSuccess' => "function(event, val, form, data) { window.location.replace('".\yii\helpers\Url::to(['skenario1/index?id_tahun_ajar='.$tahun_ajar->id])."'); }",
                        ],
                        'afterInput' => \yii\helpers\Html::hiddenInput('kuota', ceil($model->kuota)),
                        'editableButtonOptions' => [
                            'disabled' => true,
                        ],
                    ];
                } else {
                    return [
                        'format' => \kartik\editable\Editable::FORMAT_BUTTON,
                        'inputType' => \kartik\editable\Editable::INPUT_TEXT,
                        'asPopover' => false,
                        'ajaxSettings' => [
                            'url' => \yii\helpers\Url::to(['skenario1/alokasi-beasiswa?id='.$model->id_skenario]),
                        ],
                        'pluginEvents' => [
                            'editableSuccess' => "function(event, val, form, data) { window.location.replace('".\yii\helpers\Url::to(['skenario1/index?id_tahun_ajar='.$tahun_ajar->id])."'); }",
                        ],
                        'afterInput' => \yii\helpers\Html::hiddenInput('kuota', ceil($model->kuota)),
                        'editableButtonOptions' => [
                            'disabled' => $model->diambil == null ? true : false,
                            'class' => $model->diambil == null ? null : 'btn btn-sm',
                        ],
                    ];
                }
            },
        ],
        [
            'class' => 'kartik\grid\EditableColumn',
            'hAlign' => \kartik\grid\GridView::ALIGN_RIGHT,
            'attribute' => 'request',
            'editableOptions' => function ($model, $key, $index) use ($tahun_ajar) {
                if (date('Y-m-d') > date('Y-m-d', strtotime($tahun_ajar->akhir))) {
                    return [
                        'format' => \kartik\editable\Editable::FORMAT_BUTTON,
                        'inputType' => \kartik\editable\Editable::INPUT_TEXT,
                        'asPopover' => false,
                        'ajaxSettings' => [
                            'url' => \yii\helpers\Url::to(['skenario1/alokasi-beasiswa?id='.$model->id_skenario]),
                        ],
                        'pluginEvents' => [
                            'editableSuccess' => "function(event, val, form, data) { window.location.replace('".\yii\helpers\Url::to(['skenario1/index?id_tahun_ajar='.$tahun_ajar->id])."'); }",
                        ],
                        'afterInput' => \yii\helpers\Html::hiddenInput('kuota', ceil($model->kuota)),
                        'editableButtonOptions' => [
                            'disabled' => true,
                        ],
                    ];
                } else {
                    return [
                        'format' => \kartik\editable\Editable::FORMAT_BUTTON,
                        'inputType' => \kartik\editable\Editable::INPUT_TEXT,
                        'asPopover' => false,
                        'ajaxSettings' => [
                            'url' => \yii\helpers\Url::to(['skenario1/alokasi-beasiswa?id='.$model->id_skenario]),
                        ],
                        'pluginEvents' => [
                            'editableSuccess' => "function(event, val, form, data) { window.location.replace('".\yii\helpers\Url::to(['skenario1/index?id_tahun_ajar='.$tahun_ajar->id])."'); }",
                        ],
                        'afterInput' => \yii\helpers\Html::hiddenInput('kuota', ceil($model->kuota)),
                        'editableButtonOptions' => [
                            'disabled' => $model->request == null ? true : false,
                            'class' => $model->request == null ? null : 'btn btn-sm',
                        ],
                    ];
                }
            },
        ],
        [
            'headerOptions' => ['style' => 'width:7%'],
            'attribute' => 'kuota_fix',
            'format' => 'raw',
        ],

    ],
]); ?>