<?=  \kartik\grid\GridView::widget([
    'dataProvider' => $dataProvider,
    //'showFooter'=>TRUE,
    'pager' => [
        'class' => yii\widgets\LinkPager::className(),
        'firstPageLabel' => 'First',
        'lastPageLabel' => 'Last',
    ],
    'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
    'headerRowOptions' => ['class' => 'x'],
    'panel' => [
        'type' => \kartik\grid\GridView::TYPE_PRIMARY,
        'heading' => '<span class="glyphicon glyphicon-book"></span> Beasiswa ',
    ],
    'toolbar' => false,
    'columns' => [
        ['class' => 'kartik\grid\SerialColumn'],
        // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
        [
            'class' => yii\grid\DataColumn::className(),
            'attribute' => 'awal',
            'label' => 'Tahun Ajar',
            'value' => function ($model) {
                $formatter = Yii::$app->formatter;
                return $formatter->asDate($model->awal).' / '.$formatter->asDate($model->akhir);
            },
            'format' => 'raw',
        ],
        [
            'attribute' => 'nominal',
            'format' => 'raw',
            'value' => function ($model) {
                return Yii::$app->runAction('kegiatan/rupiah', ['nilai' => $model->nominal]);
            },
        ],
        [
            'headerOptions' => ['style' => 'width:5%'],
            'attribute' => 'kuota',
            'format' => 'raw',
            'value' => function($model) {
                return ceil($model->kuota);
            },
        ],
        [
            'class' => 'kartik\grid\EditableColumn',
            'hAlign' => \kartik\grid\GridView::ALIGN_RIGHT,
            'attribute' => 'diambil',
            'format' => 'raw',
            'editableOptions' => function ($model, $key, $index) {
                $now = date('Y-m-d');
                if ($model->jeda_akhir == 1) {
                    $pause = date('Y-m-d', strtotime($model->akhir));

                    if($now == $pause) {
                        return [
                            'format' => \kartik\editable\Editable::FORMAT_BUTTON,
                            'inputType' => \kartik\editable\Editable::INPUT_TEXT,
                            'asPopover' => false,
                            'ajaxSettings' => [
                                'url' => \yii\helpers\Url::to(['skenario1/alokasi-beasiswa?id='.$model->id_skenario]),
                            ],
                            'afterInput' => \yii\helpers\Html::hiddenInput('kuota', ceil($model->kuota)),
                            'pluginEvents' => [
                                'editableSuccess' => "function(event, val, form, data) { location.reload(); }",
                            ],
                            'editableButtonOptions' => [
                                'disabled' => false,
                                'class' => 'btn btn-sm',
                            ],
                        ];
                    } else {
                        return [
                            'format' => \kartik\editable\Editable::FORMAT_BUTTON,
                            'inputType' => \kartik\editable\Editable::INPUT_TEXT,
                            'asPopover' => false,
                            'ajaxSettings' => [
                                'url' => \yii\helpers\Url::to(['skenario1/alokasi-beasiswa?id='.$model->id_skenario]),
                            ],
                            'afterInput' => \yii\helpers\Html::hiddenInput('kuota', ceil($model->kuota)),
                            'pluginEvents' => [
                                'editableSuccess' => "function(event, val, form, data) { location.reload(); }",
                            ],
                            'editableButtonOptions' => [
                                'disabled' => true,
                            ],
                        ];
                    }
                } else {
                    $startPause = date('Y-m-d', strtotime('-'.($model->jeda_akhir - 1).'days', strtotime($model->akhir)));
                    $endPause = date('Y-m-d', strtotime($model->akhir));

                    if($now >= $startPause && $now <= $endPause) {
                        return [
                            'format' => \kartik\editable\Editable::FORMAT_BUTTON,
                            'inputType' => \kartik\editable\Editable::INPUT_TEXT,
                            'asPopover' => false,
                            'ajaxSettings' => [
                                'url' => \yii\helpers\Url::to(['skenario1/alokasi-beasiswa?id='.$model->id_skenario]),
                            ],
                            'afterInput' => \yii\helpers\Html::hiddenInput('kuota', ceil($model->kuota)),
                            'pluginEvents' => [
                                'editableSuccess' => "function(event, val, form, data) { location.reload(); }",
                            ],
                            'editableButtonOptions' => [
                                'disabled' => false,
                                'class' => 'btn btn-sm',
                            ],
                        ];
                    } else {
                        return [
                            'format' => \kartik\editable\Editable::FORMAT_BUTTON,
                            'inputType' => \kartik\editable\Editable::INPUT_TEXT,
                            'asPopover' => false,
                            'ajaxSettings' => [
                                'url' => \yii\helpers\Url::to(['skenario1/alokasi-beasiswa?id='.$model->id_skenario]),
                            ],
                            'afterInput' => \yii\helpers\Html::hiddenInput('kuota', ceil($model->kuota)),
                            'pluginEvents' => [
                                'editableSuccess' => "function(event, val, form, data) { location.reload(); }",
                            ],
                            'editableButtonOptions' => [
                                'disabled' => true,
                            ],
                        ];
                    }
                }
            },
        ],
        [
            'class' => 'kartik\grid\EditableColumn',
            'hAlign' => \kartik\grid\GridView::ALIGN_RIGHT,
            'attribute' => 'request',
            'editableOptions' => function ($model, $key, $index) {
                $now = date('Y-m-d');
                if ($model->jeda_akhir == 1) {
                    $pause = date('Y-m-d', strtotime($model->akhir));

                    if($now == $pause) {
                        return [
                            'format' => \kartik\editable\Editable::FORMAT_BUTTON,
                            'inputType' => \kartik\editable\Editable::INPUT_TEXT,
                            'asPopover' => false,
                            'ajaxSettings' => [
                                'url' => \yii\helpers\Url::to(['skenario1/alokasi-beasiswa?id='.$model->id_skenario]),
                            ],
                            'afterInput' => \yii\helpers\Html::hiddenInput('kuota', ceil($model->kuota)),
                            'editableButtonOptions' => [
                                'disabled' => false,
                                'class' => 'btn btn-sm',
                            ],
                        ];
                    } else {
                        return [
                            'format' => \kartik\editable\Editable::FORMAT_BUTTON,
                            'inputType' => \kartik\editable\Editable::INPUT_TEXT,
                            'asPopover' => false,
                            'ajaxSettings' => [
                                'url' => \yii\helpers\Url::to(['skenario1/alokasi-beasiswa?id='.$model->id_skenario]),
                            ],
                            'afterInput' => \yii\helpers\Html::hiddenInput('kuota', ceil($model->kuota)),
                            'editableButtonOptions' => [
                                'disabled' => true,
                            ],
                        ];
                    }
                } else {
                    $startPause = date('Y-m-d', strtotime('-'.($model->jeda_akhir - 1).'days', strtotime($model->akhir)));
                    $endPause = date('Y-m-d', strtotime($model->akhir));

                    if($now >= $startPause && $now <= $endPause) {
                        return [
                            'format' => \kartik\editable\Editable::FORMAT_BUTTON,
                            'inputType' => \kartik\editable\Editable::INPUT_TEXT,
                            'asPopover' => false,
                            'ajaxSettings' => [
                                'url' => \yii\helpers\Url::to(['skenario1/alokasi-beasiswa?id='.$model->id_skenario]),
                            ],
                            'afterInput' => \yii\helpers\Html::hiddenInput('kuota', ceil($model->kuota)),
                            'editableButtonOptions' => [
                                'disabled' => false,
                                'class' => 'btn btn-sm',
                            ],
                        ];
                    } else {
                        return [
                            'format' => \kartik\editable\Editable::FORMAT_BUTTON,
                            'inputType' => \kartik\editable\Editable::INPUT_TEXT,
                            'asPopover' => false,
                            'ajaxSettings' => [
                                'url' => \yii\helpers\Url::to(['skenario1/alokasi-beasiswa?id='.$model->id_skenario]),
                            ],
                            'afterInput' => \yii\helpers\Html::hiddenInput('kuota', ceil($model->kuota)),
                            'editableButtonOptions' => [
                                'disabled' => true,
                            ],
                        ];
                    }
                }
            },
        ],
        [
            'headerOptions' => ['style' => 'width:7%'],
            'attribute' => 'kuota_fix',
            'format' => 'raw',
        ],
    ],
]); ?>