<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var app\models\Skenario1 $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="skenario1-form">

    <?php $form = ActiveForm::begin([
    'id' => 'Skenario1',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error'
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            

<!-- attribute id_mitra -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'id_mitra')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\MasterMitra::find()->all(), 'id', 'id'),
    [
        'prompt' => 'Select',
        'disabled' => (isset($relAttributes) && isset($relAttributes['id_mitra'])),
    ]
); ?>

<!-- attribute id_tahun_ajar -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'id_tahun_ajar')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\MasterTahunAjar::find()->all(), 'id', 'id'),
    [
        'prompt' => 'Select',
        'disabled' => (isset($relAttributes) && isset($relAttributes['id_tahun_ajar'])),
    ]
); ?>

<!-- attribute jatah_kuota -->
			<?= $form->field($model, 'jatah_kuota')->textInput() ?>

<!-- attribute nominal_terbayar -->
			<?= $form->field($model, 'nominal_terbayar')->textInput() ?>

<!-- attribute diambil -->
			<?= $form->field($model, 'diambil')->textInput() ?>

<!-- attribute request -->
			<?= $form->field($model, 'request')->textInput() ?>
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                    'encodeLabels' => false,
                    'items' => [ 
                        [
    'label'   => 'Skenario1',
    'content' => $this->blocks['main'],
    'active'  => true,
],
                    ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? 'Create' : 'Save'),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

