<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "artikel".
 *
 * @property integer $id_artikel
 * @property string $judul
 * @property string $deskripsi
 * @property string $image
 * @property string $abstrak
 * @property string $aliasModel
 */
abstract class Artikel extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'artikel';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['judul', 'deskripsi', 'abstrak'], 'string'],
            [['image'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_artikel' => 'Id Artikel',
            'judul' => 'Judul',
            'deskripsi' => 'Deskripsi',
            'image' => 'Image',
            'abstrak' => 'Abstrak',
        ];
    }




}
