<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "donasi".
 *
 * @property integer $id
 * @property integer $id_mahasiswa
 * @property integer $jumlah
 * @property string $tgl_donasi
 * @property integer $valid
 * @property string $tgl_valid
 * @property string $fakultas
 * @property string $jurusan
 * @property string $aliasModel
 */
abstract class Donasi extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'donasi';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_mahasiswa', 'jumlah', 'tgl_donasi'], 'required'],
            [['id_mahasiswa', 'jumlah', 'valid','fakultas','jurusan'], 'integer'],
            [['tgl_donasi', 'tgl_valid'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_mahasiswa' => 'Mahasiswa',
            'jumlah' => 'Jumlah',
            'tgl_donasi' => 'Tanggal Donasi',
            'valid' => 'Valid',
            'tgl_valid' => 'Tgl Valid',
        ];
    }

    public function getMahasiswa(){
        return $this->hasOne(Mahasiswa::className(), ['id' => 'id_mahasiswa']);
    }



}
