<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "donatur".
 *
 * @property integer $id
 * @property integer $donatur
 * @property string $jenis_donatur
 * @property integer $jumlah
 * @property string $aliasModel
 */
abstract class Donatur extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'donatur';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['donatur', 'jenis_donatur', 'jumlah'], 'required'],
            [['donatur', 'jumlah'], 'integer'],
            [['jenis_donatur'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'donatur' => 'Donatur',
            'jenis_donatur' => 'Jenis Donatur',
            'jumlah' => 'Jumlah',
        ];
    }




}
