<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "forum".
 *
 * @property integer $id
 * @property integer $id_kategori_forum
 * @property integer $id_jabatan
 * @property string $judul
 * @property string $isi
 * @property string $tanggal
 * @property integer $status
 * @property integer $id_mahasiswa
 *
 * @property \backend\models\KategoriForum $idKategoriForum
 * @property \backend\models\MasterJabatan $idJabatan
 * @property \app\models\Mahasiswa $idMahasiswa
 * @property \backend\models\KomentarForum[] $komentarForums
 * @property string $aliasModel
 */
abstract class Forum extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'forum';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_kategori_forum', 'id_jabatan', 'judul', 'isi', 'tanggal', 'id_mahasiswa'], 'required'],
            [['id_kategori_forum', 'id_jabatan', 'status', 'id_mahasiswa'], 'integer'],
            [['isi'], 'string'],
            [['tanggal'], 'safe'],
            [['judul'], 'string', 'max' => 250],
            [['id_kategori_forum'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\KategoriForum::className(), 'targetAttribute' => ['id_kategori_forum' => 'id']],
            [['id_jabatan'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\MasterJabatan::className(), 'targetAttribute' => ['id_jabatan' => 'id']],
            [['id_mahasiswa'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Mahasiswa::className(), 'targetAttribute' => ['id_mahasiswa' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_kategori_forum' => 'Id Kategori Forum',
            'id_jabatan' => 'Id Jabatan',
            'judul' => 'Judul',
            'isi' => 'Isi',
            'tanggal' => 'Tanggal',
            'status' => 'Status',
            'id_mahasiswa' => 'Id Mahasiswa',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdKategoriForum()
    {
        return $this->hasOne(\backend\models\KategoriForum::className(), ['id' => 'id_kategori_forum']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdJabatan()
    {
        return $this->hasOne(\backend\models\MasterJabatan::className(), ['id' => 'id_jabatan']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdMahasiswa()
    {
        return $this->hasOne(\app\models\Mahasiswa::className(), ['id' => 'id_mahasiswa']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKomentarForums()
    {
        return $this->hasMany(\backend\models\KomentarForum::className(), ['id_forum' => 'id']);
    }




}
