<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "jenis".
 *
 * @property integer $id_jenis
 * @property string $nama
 * @property string $aliasModel
 */
abstract class Jenis extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'jenis';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_jenis', 'nama'], 'required'],
            [['id_jenis'], 'integer'],
            [['nama'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_jenis' => 'Id Jenis',
            'nama' => 'Nama',
        ];
    }




}
