<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "jenis_kegiatan".
 *
 * @property integer $id
 * @property string $type_kegiatan
 *
 * @property \app\models\MasterKegiatan[] $masterKegiatans
 * @property string $aliasModel
 */
abstract class JenisKegiatan extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'jenis_kegiatan';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type_kegiatan'], 'required'],
            [['type_kegiatan'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'type_kegiatan' => 'Type Kegiatan',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMasterKegiatans()
    {
        return $this->hasMany(\app\models\MasterKegiatan::className(), ['id_jenis' => 'id']);
    }




}
