<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use backend\models\LokerSkill;
use Yii;

/**
 * This is the base-model class for table "loker".
 *
 * @property integer $id
 * @property string $judul
 * @property string $nama_kantor
 * @property string $isi
 * @property string $tanggal
 * @property string $lokasi
 * @property string $jenis_karyawan
 * @property string $email
 * @property string $kontak
 * @property string $url
 * @property integer $id_mahasiswa
 * @property integer $flag
 *
 * @property \app\models\Mahasiswa $idMahasiswa
 * @property \app\models\LokerSkill[] $lokerSkills
 * @property string $aliasModel
 */
abstract class Loker extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'loker';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['judul', 'nama_kantor', 'isi', 'tanggal', 'lokasi', 'jenis_karyawan', 'email', 'kontak', 'url', 'id_mahasiswa'], 'required'],
            [['isi'], 'string'],
            [['tanggal'], 'safe'],
            [['id_mahasiswa', 'flag'], 'integer'],
            [['judul', 'nama_kantor'], 'string', 'max' => 150],
            [['lokasi'], 'string', 'max' => 250],
            [['jenis_karyawan', 'kontak'], 'string', 'max' => 30],
            [['email', 'url'], 'string', 'max' => 50],
            [['id_mahasiswa'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Mahasiswa::className(), 'targetAttribute' => ['id_mahasiswa' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'judul' => 'Judul',
            'nama_kantor' => 'Nama Kantor',
            'isi' => 'Isi',
            'tanggal' => 'Tanggal',
            'lokasi' => 'Lokasi',
            'jenis_karyawan' => 'Jenis Karyawan',
            'email' => 'Email',
            'kontak' => 'Kontak',
            'url' => 'Url',
            'id_mahasiswa' => 'Id Mahasiswa',
            'flag' => 'Flag',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdMahasiswa()
    {
        return $this->hasOne(\app\models\Mahasiswa::className(), ['id' => 'id_mahasiswa']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLokerSkills()
    {
        return $this->hasMany(LokerSkill::className(), ['loker_id' => 'id']);
    }




}
