<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "mahasiswa".
 *
 * @property integer $id
 * @property string $nama_lengkap
 * @property string $nimrn
 * @property string $tempat_lahir
 * @property string $tanggal_lahir
 * @property string $alamat
 * @property string $tahun_masuk
 * @property integer $status
 * @property string $foto
 * @property integer $fakultas
 * @property integer $jurusan
 * @property integer $lat
 * @property integer $lng
 * @property integer $pekerjaan
 * @property integer $password_hash
 *
 * @property \app\models\Jurusan $jurusan0
 * @property \app\models\Fakultas $fakultas0
 * @property string $aliasModel
 */
abstract class Mahasiswa extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'mahasiswa';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username', 'password_hash', 'nama_lengkap', 'nimrn', 'email'], 'required'],
            [['fakultas', 'jurusan', 'aprroved'], 'integer'],
            [['lat', 'lng'], 'number'],
            [['username'], 'string', 'max' => 25],
            [['auth_key'], 'string', 'max' => 32],
            [['password_reset_token', 'email','password_hash'], 'string', 'max' => 255],
            [['nama_lengkap', 'nimrn', 'tempat_lahir', 'tanggal_lahir', 'alamat', 'pekerjaan'], 'string', 'max' => 100],
            [['tahun_masuk'], 'string', 'max' => 4],
            [['status'], 'string', 'max' => 20],
            [['deskripsi'], 'safe'],
            [['foto'], 'string', 'max' => 120],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Username',
            'auth_key' => 'Auth Key',
            'password_hash' => 'Password Hash',
            'password_reset_token' => 'Password Reset Token',
            'email' => 'Email',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'nama_lengkap' => 'Nama Lengkap',
            'nimrn' => 'NIM',
            'tempat_lahir' => 'Tempat Lahir',
            'tanggal_lahir' => 'Tanggal Lahir',
            'alamat' => 'Alamat',
            'tahun_masuk' => 'Tahun Masuk',
            'status' => 'Status',
            'foto' => 'Foto',
            'fakultas' => 'Fakultas',
            'jurusan' => 'Jurusan',
            'pekerjaan' => 'Pekerjaan',
            'lat' => 'Lat',
            'lng' => 'Lng',
            'aprroved' => 'Aprroved',
            'deskripsi' => 'Deskripsi'
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJurusan0()
    {
        return $this->hasOne(\app\models\Jurusan::className(), ['id' => 'jurusan']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFakultas0()
    {
        return $this->hasOne(\app\models\Fakultas::className(), ['id' => 'fakultas']);
    }


    public function upload()
    {
        if ($this->validate()) {
            $this->foto->saveAs(Yii::getAlias("@backend/web/uploads/mahasiswa/foto/") . $this->foto->basename . "." . $this->foto->extension);
            return true;
        } else {
            return true;
        }

    }

}
