<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "master_tahun_ajar".
 *
 * @property integer $id
 * @property string $awal
 * @property string $akhir
 * @property integer $total_kuota
 * @property integer $jeda_akhir
 * @property integer $is_calculated
 *
 * @property \app\models\MasterKegiatan[] $masterKegiatans
 * @property \app\models\Skenario1[] $skenario1s
 * @property string $aliasModel
 */
abstract class MasterTahunAjar extends \yii\db\ActiveRecord
{
    public $kuota;
    public $nominal;
    public $id_skenario;
    public $diambil;
    public $request;
    public $kuota_fix;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'master_tahun_ajar';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['awal', 'akhir', 'total_kuota', 'jeda_akhir'], 'required'],
            [['awal', 'akhir'], 'safe'],
            [['total_kuota', 'jeda_akhir', 'is_calculated'], 'integer'],
            ['awal', 'compare', 'compareAttribute' => 'akhir', 'operator' => '<', 'enableClientValidation' => false],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'awal' => 'Tanggal Berawal Tahun Ajaran',
            'akhir' => 'Tanggal Berakhir Tahun Ajaran',
            'total_kuota' => 'Total Kuota',
            'jeda_akhir' => 'Jeda Pengisian Skenario 1',
            'is_calculated' => 'Is Calculated',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMasterKegiatans()
    {
        return $this->hasMany(\app\models\MasterKegiatan::className(), ['id_tahun_ajar' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSkenario1s()
    {
        return $this->hasMany(\app\models\Skenario1::className(), ['id_tahun_ajar' => 'id']);
    }




}
