<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "master_kategori_mitra".
 *
 * @property integer $id
 * @property string $nama
 * @property string $aliasModel
  * @property \app\models\MasterMitra[] $masterMitras
 */

abstract class MasterKategoriMitra extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'master_kategori_mitra';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama'], 'required'],
            [['nama'], 'string', 'max' => 40]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
        ];
    }

         /**
     * @return \yii\db\ActiveQuery
     */
    public function getMasterMitras()
    {
        return $this->hasMany(\app\models\MasterMitra::className(), ['id_kategori' => 'id']);
    }




}
