<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "skenario1".
 *
 * @property integer $id
 * @property integer $id_mitra
 * @property integer $id_tahun_ajar
 * @property integer $kuota
 * @property integer $diambil
 * @property integer $request
 * @property integer $kuota_fix
 *
 * @property \app\models\MasterMitra $idMitra
 * @property \app\models\MasterTahunAjar $idTahunAjar
 * @property string $aliasModel
 */
abstract class Skenario1 extends \yii\db\ActiveRecord
{

    public $total_dana;
    public $total_perhitungan;
    public $total_kuota;
    public $total_diambil;
    public $total_request;
    public $mitra_aktif;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'skenario1';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_mitra', 'id_tahun_ajar', 'kuota', 'diambil'], 'required'],
            [['id_mitra', 'id_tahun_ajar', 'kuota', 'diambil', 'request', 'kuota_fix'], 'integer'],
            [['id_mitra'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\MasterMitra::className(), 'targetAttribute' => ['id_mitra' => 'id']],
            [['id_tahun_ajar'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\MasterTahunAjar::className(), 'targetAttribute' => ['id_tahun_ajar' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_mitra' => 'Id Mitra',
            'id_tahun_ajar' => 'Id Tahun Ajar',
            'kuota' => 'Kuota',
            'diambil' => 'Diambil',
            'request' => 'Request',
            'kuota_fix' => 'Kuota Fix',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdMitra()
    {
        return $this->hasOne(\app\models\MasterMitra::className(), ['id' => 'id_mitra']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdTahunAjar()
    {
        return $this->hasOne(\app\models\MasterTahunAjar::className(), ['id' => 'id_tahun_ajar']);
    }




}
