<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var app\models\Dokter $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="dokter-form">

    <?php $form = ActiveForm::begin([
    'id' => 'Dokter',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error'
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            

<!-- attribute id_no_izin -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'id_no_izin')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\IzinDokter::find()->all(), 'id_no_izin', 'id_no_izin'),
    [
        'prompt' => 'Select',
        'disabled' => (isset($relAttributes) && isset($relAttributes['id_no_izin'])),
    ]
); ?>

<!-- attribute password -->
			<?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>

<!-- attribute id_kota -->
			<?= $form->field($model, 'id_kota')->textInput() ?>

<!-- attribute id_provinsi -->
			<?= $form->field($model, 'id_provinsi')->textInput() ?>

<!-- attribute id_user -->
			<?= $form->field($model, 'id_user')->textInput() ?>

<!-- attribute email -->
			<?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

<!-- attribute alamat_rumah -->
			<?= $form->field($model, 'alamat_rumah')->textInput(['maxlength' => true]) ?>

<!-- attribute alamat_praktik -->
			<?= $form->field($model, 'alamat_praktik')->textInput(['maxlength' => true]) ?>

<!-- attribute nama_dokter -->
			<?= $form->field($model, 'nama_dokter')->textInput(['maxlength' => true]) ?>

<!-- attribute no_telp -->
			<?= $form->field($model, 'no_telp')->textInput(['maxlength' => true]) ?>
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                    'encodeLabels' => false,
                    'items' => [ 
                        [
    'label'   =>  'Dokter',
    'content' => $this->blocks['main'],
    'active'  => true,
],
                    ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? 'Create' : 'Save'),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

