<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
<<<<<<< HEAD
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
=======

>>>>>>> api
$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to signup:</p>

<<<<<<< HEAD
                    <?= $form->field($model, 'id_no_izin')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>
                    <?= $form->field($model, 'alamat_rumah') ?>
                    <?= $form->field($model, 'alamat_praktik') ?>
                    <?= $form->field($model, 'nama_dokter') ?>
                    <?= $form->field($model, 'no_telp') ?>
                    <?= $form->field($model, 'password')->passwordInput() ?>
                    
                  
                   <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
                     $form->field($model, 'id_kota')->widget(\kartik\select2\Select2::className(), [
                        'data' => ArrayHelper::map(common\models\Kabupaten::find()->all(), 'id_kab', 'nama'),
                        'options' => [
                            'prompt' => 'Pilih Kota',
                        ],
                     ])->label('Kota Tempat Tinggal'); ?>

                     <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
                     $form->field($model, 'id_provinsi')->widget(\kartik\select2\Select2::className(), [
                        'data' => ArrayHelper::map(common\models\Provinsi::find()->all(), 'id_prov', 'nama'),
                        'options' => [
                            'prompt' => 'Pilih Provinsi',
                        ],
                     ])->label('Provinsi Tinggal'); ?>

                  
                  
                    <div class="form-group">
                        <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                    </div>

                    <?php ActiveForm::end(); ?>
=======
    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
>>>>>>> api
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>
